# a2ping
# Autogenerated from man page /usr/share/man/man1/a2ping.1.gz
complete -c a2ping -s h -l help --description 'Show a summary of the usage.'
complete -c a2ping -l doc --description 'Show the man page.'
complete -c a2ping -s v --description 'Show progress and debug messages (default: no) .'
complete -c a2ping -l bboxfrom --description 'Method for determining the BoundingBox  (default: guess).'
complete -c a2ping -l papersize --description '(default: default) (bp).'
complete -c a2ping -l threshold --description 'min color for 1 in 8->1 bit conv  (default: 128) .'
complete -c a2ping -l gs-cmd --description 'path to Ghostscript program (default: gs or gswin32c).'
complete -c a2ping -l gs-ccmd --description 'path to Ghostscript for BoundingBox calculation (default: gs or gswin32c).'
complete -c a2ping -l gsextra --description 'Pass extra arguments to gs.'

