# autosp
# Autogenerated from man page /usr/share/man/man1/autosp.1.gz
complete -c autosp -s l --description '( --log ) option is used, a very detailed log  infile . alog is generated.'
complete -c autosp -s d --description '( --dotted ) option is used,  dotted  beam notes of the form \\qb{n}{.'

