# axohelp
# Autogenerated from man page /usr/share/man/man1/axohelp.1.gz
complete -c axohelp -s h -l help --description 'Gives usage information.'
complete -c axohelp -s v -l version --description 'Gives version information.'
complete -c axohelp -s V --description 'NOT CURRENTLY IMPLEMENTED: Give information on each function used.'

