# bibtexu
# Autogenerated from man page /usr/share/man/man1/bibtexu.1.gz
complete -c bibtexu -s '?' -l help --description 'display some brief help text.'
complete -c bibtexu -s d -l debug --description 'report debugging information.'
complete -c bibtexu -s s -l statistics --description 'report internal statistics.'
complete -c bibtexu -s t -l trace --description 'report execution tracing.'
complete -c bibtexu -s v -l version --description 'report BibTeX version.'
complete -c bibtexu -s l -l language --description 'use language LANG to convert strings to low case.'
complete -c bibtexu -s o -l location --description 'use language LANG for sorting.  This argument is passed to ICU library.'
complete -c bibtexu -s B -l big --description 'set large BibTeX capacity.'
complete -c bibtexu -s H -l huge --description 'set huge BibTeX capacity.'
complete -c bibtexu -s W -l wolfgang --description 'set really huge BibTeX capacity for Wolfgang.'
complete -c bibtexu -s M -l min_crossrefs --description 'set min_crossrefs to ##.'
complete -c bibtexu -l mstrings --description 'allow ## unique strings.'

