# bundle-viz2
# Autogenerated from man page /usr/share/man/man1/bundle-viz2.7.1.gz
complete -c bundle-viz2 -l file -s f --description 'The name to use for the generated file.  See --format option .'
complete -c bundle-viz2 -l format -s F --description 'This is output format option.  Supported format is png, jpg, svg, dot .'
complete -c bundle-viz2 -l requirements -s R --description 'Set to show the version of each required dependency.'
complete -c bundle-viz2 -l version -s v --description 'Set to show each gem version.'

