# bundle-lock2
# Autogenerated from man page /usr/share/man/man1/bundle-lock2.7.1.gz
complete -c bundle-lock2 -l update --description 'Ignores the existing lockfile.  Resolve then updates lockfile.'
complete -c bundle-lock2 -l local --description 'Do not attempt to connect to rubygems. org.'
complete -c bundle-lock2 -l print --description 'Prints the lockfile to STDOUT instead of writing to the file system.'
complete -c bundle-lock2 -l lockfile --description 'The path where the lockfile should be written to.'
complete -c bundle-lock2 -l full-index --description 'Fall back to using the single-file index of all gems.'
complete -c bundle-lock2 -l add-platform --description 'Add a new platform to the lockfile, re-resolving for the addition of that pla…'
complete -c bundle-lock2 -l remove-platform --description 'Remove a platform from the lockfile.'
complete -c bundle-lock2 -l patch --description 'If updating, prefer updating only to next patch version.'
complete -c bundle-lock2 -l minor --description 'If updating, prefer updating only to next minor version.'
complete -c bundle-lock2 -l major --description 'If updating, prefer updating to next major version (default).'
complete -c bundle-lock2 -l strict --description 'If updating, do not allow any gem to be updated past latest --patch | --minor…'

