# bundle-binstubs2
# Autogenerated from man page /usr/share/man/man1/bundle-binstubs2.7.1.gz
complete -c bundle-binstubs2 -l force --description 'Overwrite existing binstubs if they exist.'
complete -c bundle-binstubs2 -l path --description 'The location to install the specified binstubs to.  This defaults to bin.'
complete -c bundle-binstubs2 -l standalone --description 'Makes binstubs that can work without depending on Rubygems or Bundler at runt…'

