# bundle-update2
# Autogenerated from man page /usr/share/man/man1/bundle-update2.7.1.gz
complete -c bundle-update2 -l all --description 'Update all gems specified in Gemfile.'
complete -c bundle-update2 -l group -s g --description 'Only update the gems in the specified group.'
complete -c bundle-update2 -l source --description 'The name of a :git or :path source used in the Gemfile(5).'
complete -c bundle-update2 -l local --description 'Do not attempt to fetch gems remotely and use the gem cache instead.'
complete -c bundle-update2 -l ruby --description 'Update the locked version of Ruby to the current version of Ruby.'
complete -c bundle-update2 -l bundler --description 'Update the locked version of bundler to the invoked bundler version.'
complete -c bundle-update2 -l full-index --description 'Fall back to using the single-file index of all gems.'
complete -c bundle-update2 -l jobs -s j --description 'Specify the number of jobs to run in parallel.  The default is 1.'
complete -c bundle-update2 -l retry --description 'Retry failed network or git requests for number times.'
complete -c bundle-update2 -l quiet --description 'Only output warnings and errors.'
complete -c bundle-update2 -l redownload --description 'Force downloading every gem.'
complete -c bundle-update2 -l patch --description 'Prefer updating only to next patch version.'
complete -c bundle-update2 -l minor --description 'Prefer updating only to next minor version.'
complete -c bundle-update2 -l major --description 'Prefer updating to next major version (default).'
complete -c bundle-update2 -l strict --description 'Do not allow any gem to be updated past latest --patch | --minor | --major.'

