# bundle2
# Autogenerated from man page /usr/share/man/man1/bundle2.7.1.gz
complete -c bundle2 -l no-color --description 'Print all output without color .'
complete -c bundle2 -l retry -s r --description 'Specify the number of times you wish to attempt network commands .'

