# bundle-outdated2
# Autogenerated from man page /usr/share/man/man1/bundle-outdated2.7.1.gz
complete -c bundle-outdated2 -l local --description 'Do not attempt to fetch gems remotely and use the gem cache instead.'
complete -c bundle-outdated2 -l pre --description 'Check for newer pre-release gems.'
complete -c bundle-outdated2 -l source --description 'Check against a specific source.'
complete -c bundle-outdated2 -l strict --description 'Only list newer versions allowed by your Gemfile requirements.'
complete -c bundle-outdated2 -l parseable -l porcelain --description 'Use minimal formatting for more parseable output.'
complete -c bundle-outdated2 -l group --description 'List gems from a specific group.'
complete -c bundle-outdated2 -l groups --description 'List gems organized by groups.'
complete -c bundle-outdated2 -l update-strict --description 'Strict conservative resolution, do not allow any gem to be updated past lates…'
complete -c bundle-outdated2 -l minor --description 'Prefer updating only to next minor version.'
complete -c bundle-outdated2 -l major --description 'Prefer updating to next major version (default).'
complete -c bundle-outdated2 -l patch --description 'Prefer updating only to next patch version.'
complete -c bundle-outdated2 -l filter-major --description 'Only list major newer versions.'
complete -c bundle-outdated2 -l filter-minor --description 'Only list minor newer versions.'
complete -c bundle-outdated2 -l filter-patch --description 'Only list patch newer versions.'

