# bundle-list2
# Autogenerated from man page /usr/share/man/man1/bundle-list2.7.1.gz
complete -c bundle-list2 -l name-only --description 'Print only the name of each gem.'
complete -c bundle-list2 -l paths --description 'Print the path to each gem in the bundle.'
complete -c bundle-list2 -l without-group --description 'Print all gems expect from a group.'

