# bundle-add2
# Autogenerated from man page /usr/share/man/man1/bundle-add2.7.1.gz
complete -c bundle-add2 -l version -s v --description 'Specify version requirements(s) for the added gem.'
complete -c bundle-add2 -l group -s g --description 'Specify the group(s) for the added gem.'
complete -c bundle-add2 -l source -s s --description 'Specify the source for the added gem.'
complete -c bundle-add2 -l git --description 'Specify the git source for the added gem.'
complete -c bundle-add2 -l branch --description 'Specify the git branch for the added gem.'
complete -c bundle-add2 -l skip-install --description 'Adds the gem to the Gemfile but does not install it.'
complete -c bundle-add2 -l optimistic --description 'Adds optimistic declaration of version .'

