# bundle-check2
# Autogenerated from man page /usr/share/man/man1/bundle-check2.7.1.gz
complete -c bundle-check2 -l dry-run --description 'Locks the [Gemfile(5)][Gemfile(5)] before running the command.'
complete -c bundle-check2 -l gemfile --description 'Use the specified gemfile instead of the [Gemfile(5)][Gemfile(5)].'

