# cct
# Autogenerated from man page /usr/share/man/man1/cct.1.gz
complete -c cct -s c --description 'Specify input columns for (up to) 4 input parameters.  Defaults to 1,2,3,4.'
complete -c cct -s d --description 'UNINDENT . sp New in version 5. 2.'
complete -c cct -s I --description 'Do the inverse transformation. UNINDENT NDENT 0. 0.'
complete -c cct -s o -l output --description 'Specify the name of the output file. UNINDENT NDENT 0. 0.'
complete -c cct -s t -l time --description 'Specify a fixed observation time to be used for all input data.'
complete -c cct -s z -l height --description 'Specify a fixed observation height to be used for all input data.'
complete -c cct -s s -l skip-lines --description 'New in version 5. 1. 0. sp Skip the first n lines of input.'
complete -c cct -s v -l verbose --description 'Write non-essential, but potentially useful, information to stderr.'
complete -c cct -l version --description 'Print version number.'

