# checksendmail
# Autogenerated from man page /usr/share/man/man8/checksendmail.8.gz
complete -c checksendmail -s a --description 'Show aliasing of local addresses in mail address resolution phase of testing.'
complete -c checksendmail -s d --description 'Precede each address translation line with ruleset sequence summary.'
complete -c checksendmail -s C --description 'Use the sendmail configuration file file.'
complete -c checksendmail -s b --description 'Use the specified sendmail_binary as the path to invoke sendmail (instead of …'
complete -c checksendmail -s l --description 'Log sendmail address test mode debugging output to log_file.'
complete -c checksendmail -s r --description 'Use resolve as the input file for the addresses to be used for mail resolving.'
complete -c checksendmail -s T --description 'Use test. address as the single address to test.'

