# chklref
# Autogenerated from man page /usr/share/man/man1/chklref.1.gz
complete -c chklref -l tex -s t --description 'Specify the TeX compiler to be used.  Default is `pdflatex`.'
complete -c chklref -l tex-options --description 'List of options to pass to the TeX compiler.'
complete -c chklref -l debug -s d --description 'Run in debug mode.  Do not clean the generated `. chk` file.'
complete -c chklref -l quiet -s q --description 'Run in quiet mode.  Do not print the output of the TeX compiler.'
complete -c chklref -l parse-only --description 'Do not run the LaTeX compiler but use the already existing `. chk` file.'
complete -c chklref -l version -s v --description 'Print the version of this script.'
complete -c chklref -l help --description 'Print this help.  AUTHOR Written by Jerome Lelong <jerome. lelong@gmail.'

