# cloud-id
# Autogenerated from man page /usr/share/man/man1/cloud-id.1.gz
complete -c cloud-id -s h -l help --description 'Show help message and exit.'
complete -c cloud-id -s j -l json --description 'Report all standardized cloud-id information as json.'
complete -c cloud-id -s l -l long --description 'Report extended cloud-id information as tab-delimited string.'
complete -c cloud-id -s i -l instance-data --description 'Path to instance-data. json file.  Default is /run/cloud-init/instance-data.'

