# cloud-init
# Autogenerated from man page /usr/share/man/man1/cloud-init.1.gz
complete -c cloud-init -s h -l help --description 'Show help message and exit.'
complete -c cloud-init -s d -l debug --description 'Show additional pre-action logging (default: False).'
complete -c cloud-init -s f -l files --description 'Additional YAML configuration files to use.'
complete -c cloud-init -l force --description 'Force running even if no datasource is found (use at your own risk).'
complete -c cloud-init -s v -l version --description 'Show program\'s version number and exit.'

