# compel
# Autogenerated from man page /usr/share/man/man1/compel.1.gz
complete -c compel -s f -l file --description '.'
complete -c compel -s o -l output --description '.'
complete -c compel -s p -l prefix --description '.'
complete -c compel -s l -l log-level --description '.'
complete -c compel -s h -l help --description '.'
complete -c compel -s V -l version --description '.'

