# create-munge-key
# Autogenerated from man page /usr/share/man/man8/create-munge-key.8.gz
complete -c create-munge-key -s h --description 'Display a summary of the command-line options.'
complete -c create-munge-key -s r --description 'specify /dev/random as random file for key generation default is /dev/urandom…'
complete -c create-munge-key -s f --description 'Force overwriting existing old key.'

