# ctangle
# Autogenerated from man page /usr/share/man/man1/ctangle.1.gz
complete -c ctangle -l version -s i -s o --description '+lX are new in CWEBbin and TeX Live.'
complete -c ctangle -l verbose --description '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c ctangle -l quiet --description '[bu] 2 +v/-v: shortcut for +bhp; also.'
complete -c ctangle -l help --description '[bu] 2.'
complete -c ctangle -s e --description '[bu] 2.'
complete -c ctangle -s f --description 'output [bu] 2.'
complete -c ctangle -s x --description '[bu] 2 +lX/-lX: use macros for language X as of Xcwebmac. tex ENVIRONMENT.'

