# ctanbib
# Autogenerated from man page /usr/share/man/man1/ctanbib.1.gz
complete -c ctanbib -s c -l ctan --description 'use @ctan type instead of @manual.'
complete -c ctanbib -s h -l help --description 'print the help message.'
complete -c ctanbib -s v -l version --description 'print the version info.  EXAMPLES.'

