# ctwill
# Autogenerated from man page /usr/share/man/man1/ctwill.1.gz
complete -c ctwill -l version -s i -s o --description '+lX are new in CWEBbin and TeX Live.'
complete -c ctwill -l verbose --description '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c ctwill -l quiet --description '[bu] 2 +v/-v: shortcut for +bhp; also.'
complete -c ctwill -s e --description '[bu] 2.'
complete -c ctwill -s f --description 'output [bu] 2.'
complete -c ctwill -s x --description '[bu] 2 +P: [rs]input ctproofmac. tex instead of ctwimac.'
complete -c ctwill -l help --description '[bu] 2.'

