# ctwill-refsort
# Autogenerated from man page /usr/share/man/man1/ctwill-refsort.1.gz
complete -c ctwill-refsort -l version -s i -s o --description '+lX are new in CWEBbin and TeX Live.'
complete -c ctwill-refsort -l verbose --description '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c ctwill-refsort -l quiet --description '[bu] 2 +v/-v: shortcut for +bhp; also.'
complete -c ctwill-refsort -s e --description '[bu] 2.'
complete -c ctwill-refsort -s f --description 'output [bu] 2.'
complete -c ctwill-refsort -s x --description '[bu] 2 +P: [rs]input ctproofmac. tex instead of ctwimac.'
complete -c ctwill-refsort -l help --description '[bu] 2.'

