# cuda-gdb
# Autogenerated from man page /usr/share/man/man1/cuda-gdb.1
complete -c cuda-gdb -l cuda-use-lockfile --description 'If VALUE is 0, CUDA-GDB will not create a lock file and will not enforce the …'

