# cweave
# Autogenerated from man page /usr/share/man/man1/cweave.1.gz
complete -c cweave -l version -s i -s o --description '+lX are new in CWEBbin and TeX Live.'
complete -c cweave -l verbose --description '[bu] 2 File lookup with the environment variable CWEBINPUTS is extended to pe…'
complete -c cweave -l quiet --description '[bu] 2 +v/-v: shortcut for +bhp; also.'
complete -c cweave -l help --description '[bu] 2.'
complete -c cweave -s e --description '[bu] 2.'
complete -c cweave -s f --description 'output [bu] 2.'
complete -c cweave -s x --description '[bu] 2 +lX/-lX: use macros for language X as of Xcwebmac. tex ENVIRONMENT.'

