# dumpsexp
# Autogenerated from man page /usr/share/man/man1/dumpsexp.1.gz
complete -c dumpsexp -l decimal --description 'Print offsets using decimal notation.'
complete -c dumpsexp -l assume-hex --description 'Assume input is a hex dump.'
complete -c dumpsexp -l verbose --description 'Show what we are doing.'
complete -c dumpsexp -l version --description 'Print version of the program and exit.'
complete -c dumpsexp -l help --description 'Display this help and exit REPORTING BUGS Report bugs to <bug-libgcrypt@gnupg.'

