# eptex
# Autogenerated from man page /usr/share/man/man1/eptex.1.gz
complete -c eptex -o kanji --description 'Sets the input Japanese Kanji code.'
complete -c eptex -o kanji-internal --description 'Sets the internal Kanji code.   The string can be either R euc , and R sjis .'
complete -c eptex -o enc --description 'In this version of (e-)(u)p, enc extensions are not available.'

