# expn
# Autogenerated from man page /usr/share/man/man1/expn.1.gz
complete -c expn -o aa --description 'flag, only expansions that result in legal addresses are used.'
complete -c expn -s a --description 'address, flag specifies that a few illegal addresses can be mixed into the re…'
complete -c expn -s 1 --description 'option.   For each .'
complete -c expn -o 111 --description 'will traverse no more than three levels deep.'
complete -c expn -s v --description 'verbose, flag will cause  expn  to show each address before and after transla…'
complete -c expn -s w --description 'watch, flag will cause expn to show you its conversations with the mail daemo…'
complete -c expn -s d --description 'debug, flag will expose many of the inner workings so that it is possible to …'

