# fail2ban-testcases
# Autogenerated from man page /usr/share/man/man1/fail2ban-testcases.1.gz
complete -c fail2ban-testcases -l version --description 'show program\'s version number and exit.'
complete -c fail2ban-testcases -s h -l help --description 'show this help message and exit.'
complete -c fail2ban-testcases -s l -l log-level --description 'Log level for the logger to use during running tests.'
complete -c fail2ban-testcases -s v --description 'Increase verbosity.'
complete -c fail2ban-testcases -l verbosity --description 'Set numerical level of verbosity (0. 4).'
complete -c fail2ban-testcases -l log-direct --description 'Prevent lazy logging inside tests.'
complete -c fail2ban-testcases -s n -l no-network --description 'Do not run tests that require the network.'
complete -c fail2ban-testcases -s g -l no-gamin --description 'Do not run tests that require the gamin.'
complete -c fail2ban-testcases -s m -l memory-db --description 'Run database tests using memory instead of file.'
complete -c fail2ban-testcases -s f -l fast --description 'Try to increase speed of the tests, decreasing of wait intervals, memory data…'
complete -c fail2ban-testcases -s i -l ignore --description 'negate [regexps] filter to ignore tests matched specified regexps.'
complete -c fail2ban-testcases -s t -l log-traceback --description 'Enrich log-messages with compressed tracebacks.'
complete -c fail2ban-testcases -l full-traceback --description 'Either to make the tracebacks full, not compressed (as by default) SEE ALSO.'

