# fuse-overlayfs
# Autogenerated from man page /usr/share/man/man1/fuse-overlayfs.1.gz
complete -c fuse-overlayfs -l debug --description 'Enable debugging mode, can be very noisy.'
complete -c fuse-overlayfs -s o --description 'A list of directories separated by :.   Their content is merged.'
complete -c fuse-overlayfs -o ouidmapping --description 'which is the namespace configuration specified on a single line, we\'d see fro…'

