# gdal-config
# Autogenerated from man page /usr/share/man/man1/gdal-config.1.gz
complete -c gdal-config -l prefix --description 'the top level directory for the GDAL installation.'
complete -c gdal-config -l libs --description 'The libraries and link directives required to use GDAL.'
complete -c gdal-config -l cflags --description 'The include and macro definition required to compiled modules using GDAL.'
complete -c gdal-config -l version --description 'Reports the GDAL version.'
complete -c gdal-config -l ogr-enabled --description 'Reports \'yes\' or \'no\' to standard output depending on whether OGR is built in…'
complete -c gdal-config -l formats --description 'Reports which formats are configured into GDAL to stdout.'

