# geod
# Autogenerated from man page /usr/share/man/man1/geod.1.gz
complete -c geod -s I --description 'Specifies that the inverse geodesic computation is to be performed.'
complete -c geod -s a --description 'Latitude and longitudes of the initial and terminal points, forward and back …'
complete -c geod -o 't<a>' --description 'Where a specifies a character employed as the first character to denote a con…'
complete -c geod -o le --description 'Gives a listing of all the ellipsoids that may be selected with the +ellps= o…'
complete -c geod -o lu --description 'Gives a listing of all the units that may be selected with the +units= option.'
complete -c geod -s f --description 'Where format is a printf format string to control the output form of the geog…'
complete -c geod -s F --description 'Where format is a printf format string to control the output form of the dist…'
complete -c geod -o 'w<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'
complete -c geod -o 'W<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'
complete -c geod -s p --description 'This option causes the azimuthal values to be output as unsigned DMS numbers …'
complete -c geod -o '66d31\'50.141' --description 'where the first two values are the azimuth from Boston to Portland, the back …'

