# geos-config
# Autogenerated from man page /usr/share/man/man1/geos-config.1.gz
complete -c geos-config -l prefix --description 'print the prefix used by geos.'
complete -c geos-config -l version --description 'print the GEOS version.'
complete -c geos-config -l libs --description 'print the linker flags that are necessary to link to GEOS.'
complete -c geos-config -l cflags --description 'print the compiler flags that are necessary to compile a plug-in.'
complete -c geos-config -l includes --description 'show location of C++ header files.'

