# gie
# Autogenerated from man page /usr/share/man/man1/gie.1.gz
complete -c gie -s h -l help --description 'Print usage information . UNINDENT NDENT 0. 0.'
complete -c gie -s o -l output --description 'Specify output file name . UNINDENT NDENT 0. 0.'
complete -c gie -s v -l verbose --description 'Verbose: Provide non-essential informational output.'
complete -c gie -s q -l quiet --description 'Quiet: Opposite of verbose.  In quiet mode not even errors are reported.'
complete -c gie -s l -l list --description 'List the PROJ internal system error codes . UNINDENT NDENT 0. 0.'
complete -c gie -l version --description 'Print version number Tests for gie are defined in simple text files.'
complete -c gie -l ------------------------------------------ --description 'Test output of the UTM projection.'
complete -c gie -l ----------------------------------------------------------------------------- --description 'Reading file \'test. gie\' ** Mercator projection test **.'

