# h5cc
# Autogenerated from man page /usr/share/man/man1/h5cc.1.gz
complete -c h5cc -o help --description 'Prints a help message.'
complete -c h5cc -o echo --description 'Show all the shell commands executed.'
complete -c h5cc -o prefix --description 'Use the directory DIR to find the HDF5 lib/ and include/ subdirectories.'
complete -c h5cc -o show --description 'Show the commands without executing them.'
complete -c h5cc -o shlib --description 'Compile using shared HDF5 libraries.'
complete -c h5cc -o noshlib --description 'Compile using static HDF5 libraries [default].'

