# h5fc
# Autogenerated from man page /usr/share/man/man1/h5fc.1.gz
complete -c h5fc -o help --description 'This help message.'
complete -c h5fc -o echo --description 'Show all the shell commands executed.'
complete -c h5fc -o prefix --description 'Prefix directory to find HDF5 lib/ and include/ P subdirectories [default: /u…'
complete -c h5fc -o show --description 'Show the commands without executing them.'
complete -c h5fc -o showconfig --description 'Show the HDF5 library configuration summary.'
complete -c h5fc -o shlib --description 'Compile with shared HDF5 libraries.'
complete -c h5fc -o noshlib --description 'Compile with static HDF5 libraries [default].'

