# h5pfc
# Autogenerated from man page /usr/share/man/man1/h5pfc.1.gz
complete -c h5pfc -o help --description 'This help message.'
complete -c h5pfc -o echo --description 'Show all the shell commands executed.'
complete -c h5pfc -o prefix --description 'Prefix directory to find HDF5 lib/ and include/ P subdirectories [default: /u…'
complete -c h5pfc -o show --description 'Show the commands without executing them.'
complete -c h5pfc -o showconfig --description 'Show the HDF5 library configuration summary.'
complete -c h5pfc -o shlib --description 'Compile with shared HDF5 libraries [default for hdf5 built without static lib…'
complete -c h5pfc -o noshlib --description 'Compile with static HDF5 libraries [default for hdf5 built with static librar…'

