# inspect
# Autogenerated from man page /usr/share/man/man1/inspect.1.gz
complete -c inspect -o license --description '.'
complete -c inspect -o copyright --description '.'
complete -c inspect -o crlf --description '.'
complete -c inspect -o link --description '.'
complete -c inspect -o path_name --description '.'
complete -c inspect -o tab --description '.'
complete -c inspect -o ascii --description '.'
complete -c inspect -o minmax --description '.'
complete -c inspect -o unnamed --description 'The default is to have all checks on; otherwise options specify desired check…'

