# l3build
# Autogenerated from man page /usr/share/man/man1/l3build.1.gz
complete -c l3build -l config -s c --description 'Sets the config(s) used for running tests.'
complete -c l3build -l date --description 'Sets the date to insert into sources.'
complete -c l3build -l dry-run --description 'Dry run for install.'
complete -c l3build -l engine -s e --description 'Sets the engine(s) to use for running test.'
complete -c l3build -l epoch --description 'Sets the epoch for tests and typesetting.'
complete -c l3build -l first --description 'Name of first test to run.'
complete -c l3build -l force -s f --description 'Force tests to run if engine is not set up.'
complete -c l3build -l halt-on-error -s H --description 'Stops running tests after the first failure.'
complete -c l3build -l last --description 'Name of last test to run.'
complete -c l3build -l pdf -s p --description 'Check/save PDF files.'
complete -c l3build -l quiet -s q --description 'Suppresses TeX output when unpacking.'
complete -c l3build -l rerun --description 'Skip setup: simply rerun tests.'
complete -c l3build -l shuffle --description 'Shuffle order of tests.'
complete -c l3build -l texmfhome --description 'Location of user texmf tree.'

