# libgcrypt-config
# Autogenerated from man page /usr/share/man/man1/libgcrypt-config.1.gz
complete -c libgcrypt-config -l version --description 'Print the currently installed version of libgcrypt on the standard output.'
complete -c libgcrypt-config -l libs --description 'Print the linker flags that are necessary to link a libgcrypt program.'
complete -c libgcrypt-config -l cflags --description 'Print the compiler flags that are necessary to compile a libgcrypt program.'
complete -c libgcrypt-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that libgcrypt wa…'
complete -c libgcrypt-config -l exec-prefix --description 'If specified, use PREFIX instead of the installation exec prefix that libgcry…'

