# llvm-ranlib-10
# Autogenerated from man page /usr/share/man/man1/llvm-ranlib-10.1.gz
complete -c llvm-ranlib-10 -s h -l help --description '.'
complete -c llvm-ranlib-10 -s v -l version --description '.'
complete -c llvm-ranlib-10 -s D --description '.'
complete -c llvm-ranlib-10 -s U --description '.'

