# llvm-size
# Autogenerated from man page /usr/share/man/man1/llvm-size.1.gz
complete -c llvm-size -l common --description 'When using Berkeley format, this is added to bss.'
complete -c llvm-size -l help -l help-hidden --description '.'
complete -c llvm-size -l help-list -l help-list-hidden --description '.'
complete -c llvm-size -l version --description '.'
complete -c llvm-size -s A --description '.'
complete -c llvm-size -s B --description '.'
complete -c llvm-size -s m -s m --description '.'
complete -c llvm-size -l arch --description '.'
complete -c llvm-size -l format --description '.'
complete -c llvm-size -s l --description '.'
complete -c llvm-size -l radix --description '.'
complete -c llvm-size -l totals --description 'Print size in radix:.'
complete -c llvm-size -s o --description '.'
complete -c llvm-size -s d --description '.'
complete -c llvm-size -s x --description '.'

