# llvm-size-10
# Autogenerated from man page /usr/share/man/man1/llvm-size-10.1.gz
complete -c llvm-size-10 -l common --description 'When using Berkeley format, this is added to bss.'
complete -c llvm-size-10 -l help -l help-hidden --description '.'
complete -c llvm-size-10 -l help-list -l help-list-hidden --description '.'
complete -c llvm-size-10 -l version --description '.'
complete -c llvm-size-10 -s A --description '.'
complete -c llvm-size-10 -s B --description '.'
complete -c llvm-size-10 -s m -s m --description '.'
complete -c llvm-size-10 -l arch --description '.'
complete -c llvm-size-10 -l format --description '.'
complete -c llvm-size-10 -s l --description '.'
complete -c llvm-size-10 -l radix --description '.'
complete -c llvm-size-10 -l totals --description 'Print size in radix:.'
complete -c llvm-size-10 -s o --description '.'
complete -c llvm-size-10 -s d --description '.'
complete -c llvm-size-10 -s x --description '.'

