# makejvf
# Autogenerated from man page /usr/share/man/man1/makejvf.1.gz
complete -c makejvf -s C --description 'Condensed ("Cho-tai") mode.'
complete -c makejvf -s K --description 'Map Kana (more exactly, non-Kanji) characters to another PS font JFM named <P…'
complete -c makejvf -s b --description 'Base line shift amount; the integer represents a relative value, using the ch…'
complete -c makejvf -s m --description 'Replace single/double quotation marks (\', \'\') with single/double prime quotat…'
complete -c makejvf -s a --description 'Name of the input AFM file used for Kana-tsume mode.'
complete -c makejvf -s k --description 'Kana-tsume (narrower spaces between Kana characters) margin amount; the integ…'
complete -c makejvf -s i --description 'Start mapped font ID from No.'
complete -c makejvf -s e --description 'Enhanced mode; the horizontal shift amount is determined from the glue/kern t…'
complete -c makejvf -s t --description 'Use <CNFfile> as a configuration file.'
complete -c makejvf -s u --description 'UCS mode.'
complete -c makejvf -s J --description 'Map single/double quote to another JIS-encoded PSfont TFM.'
complete -c makejvf -s U --description 'Map single/double quote to another UCS-encoded PSfont TFM.'
complete -c makejvf -s 3 --description 'Use set3, that is, enable non-BMP characters support (with UCS mode).'
complete -c makejvf -s H --description 'Use half-width Katakana.  EXAMPLE.'

