# messages
# Autogenerated from man page /usr/share/man/man1/messages.1.gz
complete -c messages -s q -s s -l quiet -l silent --description 'only display number of messages P Global debugging settings.'
complete -c messages -l debug-level --description 'set Mailutils debugging level .'
complete -c messages -l config-file --description 'load this configuration file; implies --no-config.'
complete -c messages -l config-lint --description 'check configuration file syntax and exit.'
complete -c messages -l config-verbose --description 'verbosely log parsing of the configuration files.'
complete -c messages -l no-config --description 'do not load site and user configuration files.'
complete -c messages -l no-site-config --description 'do not load site-wide configuration file.'
complete -c messages -l no-user-config --description 'do not load user configuration file.'
complete -c messages -l set --description 'set configuration parameter P Informational options.'
complete -c messages -l config-help --description 'show configuration file summary.'
complete -c messages -l show-config-options --description 'show compilation options.'
complete -c messages -s '?' -l help --description 'give this help list.'
complete -c messages -l usage --description 'give a short usage message.'
complete -c messages -l debug-line-info --description 'Configuration handling.'
complete -c messages -s V -l version --description 'print program version.'

