# mkpasswd
# Autogenerated from man page /usr/share/man/man1/mkpasswd.1.gz
complete -c mkpasswd -s S --description '--salt= STRING Use the  STRING as salt.'
complete -c mkpasswd -s R --description '--rounds= NUMBER Use  NUMBER rounds.'
complete -c mkpasswd -s m --description '--method= TYPE Compute the password using the  TYPE method.'
complete -c mkpasswd -s 5 --description 'Like R --method=md5crypt .'
complete -c mkpasswd -s P --description 'R NUM ", "\\c  --password-fd= NUM Read the password from file descriptor  NUM …'
complete -c mkpasswd -l salt --description 'Use the STRING as salt.'
complete -c mkpasswd -l rounds --description 'Use NUMBER rounds.'
complete -c mkpasswd -l method --description '.'
complete -c mkpasswd -l password-fd --description 'Read the password from file descriptor NUM instead of using getpass (3).'
complete -c mkpasswd -s s -l stdin --description 'Like.'

