# mountd
# Autogenerated from man page /usr/share/man/man8/mountd.8.gz
complete -c mountd -s d -l debug --description 'Turn on debugging.  Valid kinds are: all, auth, call, general and parse.'
complete -c mountd -s F -l foreground --description 'Run in foreground (do not daemonize).'
complete -c mountd -s h -l help --description 'Display usage message.'
complete -c mountd -s o -l descriptors --description 'Set the limit of the number of open file descriptors to num.'
complete -c mountd -s N -l no-nfs-version --description 'This option can be used to request that  rpc.'
complete -c mountd -s n -l no-tcp --description 'Don\'t advertise TCP for mount.'
complete -c mountd -s p -s P -l port --description 'Specifies the port number used for RPC listener sockets.'
complete -c mountd -s H -l ha-callout --description 'Specify a high availability callout program.'
complete -c mountd -s s -l state-directory-path --description 'Specify a directory in which to place statd state information.'
complete -c mountd -s r -l reverse-lookup --description 'rpc. mountd tracks IP addresses in the  rmtab file.'
complete -c mountd -s t -l num-threads -l num-threads --description 'This option specifies the number of worker threads that rpc. mountd spawns.'
complete -c mountd -s u -l no-udp --description 'Don\'t advertise UDP for mounting.'
complete -c mountd -s V -l nfs-version --description 'This option can be used to request that  rpc.'
complete -c mountd -s v -l version --description 'Print the version of  rpc. mountd and exit.'
complete -c mountd -s g -l manage-gids --description 'Accept requests from the kernel to map user id numbers into  lists of group i…'

