# mysql_config
# Autogenerated from man page /usr/share/man/man1/mysql_config.1.gz
complete -c mysql_config -l cflags --description 'C Compiler flags to find include files and critical compiler flags and define…'
complete -c mysql_config -l include --description 'for more portable options that contain only include paths.  oc o 2. 3.'
complete -c mysql_config -l cxxflags --description 'Like.'
complete -c mysql_config -l libs --description 'Libraries and options required to link with the MySQL client library.  oc o 2.'
complete -c mysql_config -l libs_r --description 'Libraries and options required to link with the thread-safe MySQL client libr…'
complete -c mysql_config -l plugindir --description 'The default plugin directory path name, defined when configuring MySQL.'
complete -c mysql_config -l port --description 'The default TCP/IP port number, defined when configuring MySQL.  oc o 2. 3.'
complete -c mysql_config -l socket --description 'The default Unix socket file, defined when configuring MySQL.  oc o 2. 3.'
complete -c mysql_config -l variable --description 'Display the value of the named configuration variable.'
complete -c mysql_config -l version --description 'Version number for the MySQL distribution.'

