# mysql_convert_table_format
# Autogenerated from man page /usr/share/man/man1/mysql_convert_table_format.1.gz
complete -c mysql_convert_table_format -l help --description '.'
complete -c mysql_convert_table_format -l force --description '.'
complete -c mysql_convert_table_format -l host --description '.'
complete -c mysql_convert_table_format -l password --description '.'
complete -c mysql_convert_table_format -l port --description '.'
complete -c mysql_convert_table_format -l socket --description '.'
complete -c mysql_convert_table_format -l type --description '.'
complete -c mysql_convert_table_format -l user --description '.'
complete -c mysql_convert_table_format -l verbose --description '.'
complete -c mysql_convert_table_format -l version --description '.'

