# mysql_setpermission
# Autogenerated from man page /usr/share/man/man1/mysql_setpermission.1.gz
complete -c mysql_setpermission -l help --description 'to display the help message, or options that indicate how to connect to the M…'
complete -c mysql_setpermission -l host --description '.'
complete -c mysql_setpermission -l password --description '.'
complete -c mysql_setpermission -l port --description '.'
complete -c mysql_setpermission -l socket --description '.'
complete -c mysql_setpermission -l user --description '.'

