# nfsdcltrack
# Autogenerated from man page /usr/share/man/man8/nfsdcltrack.8.gz
complete -c nfsdcltrack -s d -l debug --description 'Enable debug level logging.'
complete -c nfsdcltrack -s f -l foreground --description 'Log to stderr instead of syslog.'

