# nscd
# Autogenerated from man page /usr/share/man/man8/nscd.8.gz
complete -c nscd -s d --description 'Do not fork and display messages on the current tty.  El -tag -width Ds.'
complete -c nscd -s f --description 'Read configuration data from NAME.'
complete -c nscd -s g --description 'Print current configuration statistics.  El -tag -width Ds.'
complete -c nscd -s i --description 'Invalidate the specified TABLE, i.  e.  forget all data cached therein.'
complete -c nscd -s K --description 'Quit a running nscd nscd process.  El -tag -width Ds.'
complete -c nscd -s S --description 'Use a separate cache for each user.  El -tag -width Ds.'
complete -c nscd -s t --description 'Start NUMBER threads.'
complete -c nscd -s '?' --description 'Print the list of available options.  El -tag -width Ds.'
complete -c nscd -l usage --description 'Print a short usage message.  El -tag -width Ds.'
complete -c nscd -s V --description 'Print program version.  El FILES -tag -width Ds /etc/nscd.'

