# nvidia-cuda-mps-control
# Autogenerated from man page /usr/share/man/man1/nvidia-cuda-mps-control.1.gz
complete -c nvidia-cuda-mps-control -o uid --description 'Start a new MPS server for the specified user (UID).'
complete -c nvidia-cuda-mps-control -s t --description 'Shutdown the MPS control daemon process and all MPS servers.'
complete -c nvidia-cuda-mps-control -s d --description 'Start the MPS control daemon in background mode, assuming the user has enough…'
complete -c nvidia-cuda-mps-control -s f --description 'Start the MPS control daemon in foreground mode, assuming the user has enough…'
complete -c nvidia-cuda-mps-control -s h -l help --description 'Print a help message.'

