# nvidia-modprobe
# Autogenerated from man page /usr/share/man/man1/nvidia-modprobe.1.gz
complete -c nvidia-modprobe -s v -l version --description 'Print the utility version and exit.'
complete -c nvidia-modprobe -s h -l help --description 'Print usage information for the command line options and exit.'
complete -c nvidia-modprobe -l module-instance --description 'option is specified on systems with multiple NVIDIA kernel modules, nvidia-mo…'
complete -c nvidia-modprobe -l create-nvidia-device-file --description 'option is specified, nvidia-modprobe will also create the requested device fi…'
complete -c nvidia-modprobe -s c --description 'Create the NVIDIA device file with the given minor number; this option can be…'
complete -c nvidia-modprobe -s u -l unified-memory --description 'Load the NVIDIA Unified Memory kernel module or create device files for it, i…'
complete -c nvidia-modprobe -s m -l modeset --description 'Load the NVIDIA modeset kernel module and create its device file.'
complete -c nvidia-modprobe -s s -l nvswitch --description 'Load the NVIDIA kernel module and create the NVSwitch device files for each m…'
complete -c nvidia-modprobe -s l -l nvlink --description 'Load the NVIDIA kernel module and create the NVLink control device file.'
complete -c nvidia-modprobe -s f -l nvidia-capability-device-file --description 'Create the NVIDIA capability device files with the given capability /proc fil…'

