# opencv_createsamples
# Autogenerated from man page /usr/share/man/man1/opencv_createsamples.1.gz
complete -c opencv_createsamples -o info --description 'A database of positive source images.'
complete -c opencv_createsamples -o img --description 'A positive source image.'
complete -c opencv_createsamples -o vec --description 'The output file name containing the generated positive samples for training.'
complete -c opencv_createsamples -o bg --description 'The background description file (the negative sample set).'
complete -c opencv_createsamples -o num --description 'The number of positive samples to generate/train.  The default is R 1000 .'
complete -c opencv_createsamples -o bgcolor --description 'The background color (currently grayscale images are assumed); the background…'
complete -c opencv_createsamples -o inv --description 'Invert the colors.'
complete -c opencv_createsamples -o maxidev --description 'The desired maximum intensity deviation of foreground samples pixels.'
complete -c opencv_createsamples -o maxxangle --description 'The maximum rotation angle in x-direction in radians.  The default is R 1. 1 .'
complete -c opencv_createsamples -o maxyangle --description 'The maximum rotation angle in y-direction in radians.  The default is  R 1.'
complete -c opencv_createsamples -o maxzangle --description 'The maximum rotation angle in z-direction in radians.  The default is  R 0.'
complete -c opencv_createsamples -o show --description 'Show each created sample during the creation process.'
complete -c opencv_createsamples -s h --description 'For the creation of training samples, it is the resulting sample height.'
complete -c opencv_createsamples -s w --description 'For the creation of training samples, it is the resulting sample width.'

