# opencv_performance
# Autogenerated from man page /usr/share/man/man1/opencv_performance.1.gz
complete -c opencv_performance -o data --description 'The directory, in which the classifier can be found.'
complete -c opencv_performance -o info --description 'File with test samples description.'
complete -c opencv_performance -o maxSizeDiff --description 'Determine the size criterion of reference and detected coincidence.'
complete -c opencv_performance -o maxPosDiff --description 'Determine the position criterion of reference and detected coincidence.'
complete -c opencv_performance -o sf --description 'Scale the detection window in each iteration.  The default is R 1. 200000 .'
complete -c opencv_performance -o ni --description 'Don\'t save detection result to an image.'
complete -c opencv_performance -o nos --description 'Number of stages to use.  The default is  -1 (all stages are used).'
complete -c opencv_performance -o rs --description 'The default is R \\40 .'
complete -c opencv_performance -s h --description 'The sample height (must have the same value as used during creation).'
complete -c opencv_performance -s 1 --description '(all stages are used).'
complete -c opencv_performance -s w --description 'The sample width (must have the same value as used during creation).'

