# ospcat
# Autogenerated from man page /usr/share/man/man1/ospcat.1.gz
complete -c ospcat -s b -l bctf --description 'Use bctf name for output.'
complete -c ospcat -s f -l error-file --description 'Append error messages to file file.'
complete -c ospcat -s v -l version --description 'Display the program version.'
complete -c ospcat -s h -l help --description 'Show this help text.'
complete -c ospcat -s c -l catalog --description 'Use catalog sysid.'
complete -c ospcat -s C -l catalogs --description 'Arguments are catalogs, use DOCUMENT entry.'
complete -c ospcat -s D -l directory --description 'Search files in directory directory.'
complete -c ospcat -s R -l restricted --description 'Restrict file reading (for use in Web apps).'
complete -c ospcat -s P -l public-id --description 'Print the effective system id for the public id literal.'
complete -c ospcat -s S -l system-id --description 'Print the effective system id for system id literal.'
complete -c ospcat -s p -l parameter-entity --description 'Print the effective system id for parameter entity name.'
complete -c ospcat -s d -l doctype --description 'Print the effective system id for the doctype name.'
complete -c ospcat -s l -l linktype --description 'Print the effective system id for the linktype name.'
complete -c ospcat -s e -l entity --description 'Print the effective system id for entity name.'
complete -c ospcat -s n -l notation --description 'Print the effective system id for notation name.'
complete -c ospcat -s s -l declaration --description 'Print the effective system id for the SGML declaration for doctype name.'

