# ospent
# Autogenerated from man page /usr/share/man/man1/ospent.1.gz
complete -c ospent -o bbctf -l bctf --description '.'
complete -c ospent -o csysid -l catalog --description '.'
complete -c ospent -s C -l catalogs --description '.'
complete -c ospent -o Ddirectory -l directory --description '.'
complete -c ospent -o ffile -l error-file --description '.'
complete -c ospent -s h -l help --description '.'
complete -c ospent -s n -l non-sgml --description '.'
complete -c ospent -s r --description '.'
complete -c ospent -l raw --description '.'
complete -c ospent -s R -l restricted --description '.'
complete -c ospent -s v -l version --description '.'

