# pdfatfi
# Autogenerated from man page /usr/share/man/man1/pdfatfi.1.gz
complete -c pdfatfi -l help --description 'Show help text.'
complete -c pdfatfi -l version --description 'Print version number.'

