# podman-pod-rm
# Autogenerated from man page /usr/share/man/man1/podman-pod-rm.1.gz
complete -c podman-pod-rm -l all -s a --description '.'
complete -c podman-pod-rm -l ignore -s i --description '.'
complete -c podman-pod-rm -l latest -s l --description '.'
complete -c podman-pod-rm -l force -s f --description '.'
complete -c podman-pod-rm -l pod-id-file --description '.'

