# podman-network-ls
# Autogenerated from man page /usr/share/man/man1/podman-network-ls.1.gz
complete -c podman-network-ls -l filter -s f --description '.'
complete -c podman-network-ls -l format --description '.'
complete -c podman-network-ls -l noheading --description '.'
complete -c podman-network-ls -l no-trunc --description '.'
complete -c podman-network-ls -l quiet -s q --description '.'

