# podman-play-kube
# Autogenerated from man page /usr/share/man/man1/podman-play-kube.1.gz
complete -c podman-play-kube -l authfile --description '.'
complete -c podman-play-kube -l cert-dir --description '.'
complete -c podman-play-kube -l configmap --description '.'
complete -c podman-play-kube -l creds --description '.'
complete -c podman-play-kube -l ip --description '.'
complete -c podman-play-kube -l log-driver --description '.'
complete -c podman-play-kube -l mac-address --description '.'
complete -c podman-play-kube -l network -l net --description '.'
complete -c podman-play-kube -l quiet -s q --description '.'
complete -c podman-play-kube -l seccomp-profile-root --description '.'
complete -c podman-play-kube -l start --description '.'
complete -c podman-play-kube -l tls-verify --description '.'
complete -c podman-play-kube -l help -s h --description '.'

