# podman-history
# Autogenerated from man page /usr/share/man/man1/podman-history.1.gz
complete -c podman-history -l human -s H --description '.'
complete -c podman-history -l no-trunc --description '.'
complete -c podman-history -l notruncate --description '.'
complete -c podman-history -l quiet -s q --description '.'
complete -c podman-history -l format --description '.'
complete -c podman-history -l help -s h --description '.'

