# podman-load
# Autogenerated from man page /usr/share/man/man1/podman-load.1.gz
complete -c podman-load -l input -s i --description '.'
complete -c podman-load -l quiet -s q --description '.'
complete -c podman-load -l help -s h --description '.'

