# podman-generate-systemd
# Autogenerated from man page /usr/share/man/man1/podman-generate-systemd.1.gz
complete -c podman-generate-systemd -l files -s f --description '.'
complete -c podman-generate-systemd -l format --description '.'
complete -c podman-generate-systemd -l name -s n --description '.'
complete -c podman-generate-systemd -l new --description '.'
complete -c podman-generate-systemd -l no-header --description '.'
complete -c podman-generate-systemd -l time -s t --description '.'
complete -c podman-generate-systemd -l restart-policy --description '.'
complete -c podman-generate-systemd -l container-prefix --description '.'
complete -c podman-generate-systemd -l pod-prefix --description '.'
complete -c podman-generate-systemd -l separator --description '.'

