# podman-remote
# Autogenerated from man page /usr/share/man/man1/podman-remote.1.gz
complete -c podman-remote -l connection -s c --description '.'
complete -c podman-remote -l help -s h --description '.'
complete -c podman-remote -l identity --description '.'
complete -c podman-remote -l log-level --description '.'
complete -c podman-remote -l url --description '.'
complete -c podman-remote -l version --description '.'

