# podman-mount
# Autogenerated from man page /usr/share/man/man1/podman-mount.1.gz
complete -c podman-mount -l all -s a --description '.'
complete -c podman-mount -l format --description '.'
complete -c podman-mount -l latest -s l --description '.'
complete -c podman-mount -l notruncate --description '.'

