# podman-import
# Autogenerated from man page /usr/share/man/man1/podman-import.1.gz
complete -c podman-import -l change -s c --description '.'
complete -c podman-import -l message -s m --description '.'
complete -c podman-import -l quiet -s q --description '.'
complete -c podman-import -l verbose --description 'Print additional debugging information.'
complete -c podman-import -l help -s h --description '.'

