# podman-pod-top
# Autogenerated from man page /usr/share/man/man1/podman-pod-top.1.gz
complete -c podman-pod-top -l help -s h --description '.'
complete -c podman-pod-top -l latest -s l --description '.'

