# podman-system-service
# Autogenerated from man page /usr/share/man/man1/podman-system-service.1.gz
complete -c podman-system-service -l security-opt --description 'The REST API provided by podman system service is split into two parts: a com…'
complete -c podman-system-service -l time -s t --description '.'
complete -c podman-system-service -l cors --description '.'
complete -c podman-system-service -l help -s h --description '.'

