# podman-save
# Autogenerated from man page /usr/share/man/man1/podman-save.1.gz
complete -c podman-save -l compress --description '.'
complete -c podman-save -l output -s o --description '.'
complete -c podman-save -l format --description '.'
complete -c podman-save -l multi-image-archive -s m --description '.'
complete -c podman-save -l quiet -s q --description '.'
complete -c podman-save -l help -s h --description '.'

