# podman-container-prune
# Autogenerated from man page /usr/share/man/man1/podman-container-prune.1.gz
complete -c podman-container-prune -l filter --description '.'
complete -c podman-container-prune -l force -s f --description '.'
complete -c podman-container-prune -s h -l help --description 'Print usage statement.'

