# podman-logout
# Autogenerated from man page /usr/share/man/man1/podman-logout.1.gz
complete -c podman-logout -l authfile --description '.'
complete -c podman-logout -l all -s a --description '.'
complete -c podman-logout -l help -s h --description '.'

