# podman-search
# Autogenerated from man page /usr/share/man/man1/podman-search.1.gz
complete -c podman-search -l authfile --description '.'
complete -c podman-search -l filter -s f --description '.'
complete -c podman-search -l format --description '.'
complete -c podman-search -l limit --description '.'
complete -c podman-search -l list-tags --description '.'
complete -c podman-search -l no-trunc --description '.'
complete -c podman-search -l tls-verify --description '.'
complete -c podman-search -l help -s h --description '.'

