# podman-generate-kube
# Autogenerated from man page /usr/share/man/man1/podman-generate-kube.1.gz
complete -c podman-generate-kube -l filename -s f --description '.'
complete -c podman-generate-kube -l service -s s --description '.'
complete -c podman-generate-kube -l - --description 'apiVersion: v1 kind: Service metadata:   creationTimestamp: 2018-12-18T15:16:…'

