# podman-network-create
# Autogenerated from man page /usr/share/man/man1/podman-network-create.1.gz
complete -c podman-network-create -l disable-dns --description '.'
complete -c podman-network-create -l driver -s d --description '.'
complete -c podman-network-create -l opt -s o --description '.'
complete -c podman-network-create -l gateway --description '.'
complete -c podman-network-create -l internal --description '.'
complete -c podman-network-create -l ip-range --description '.'
complete -c podman-network-create -l label --description '.'
complete -c podman-network-create -l macvlan --description '.'
complete -c podman-network-create -l subnet --description '.'
complete -c podman-network-create -l ipv6 --description '.'

