# podman-volume-ls
# Autogenerated from man page /usr/share/man/man1/podman-volume-ls.1.gz
complete -c podman-volume-ls -l filter -s f --description '.'
complete -c podman-volume-ls -l format --description '.'
complete -c podman-volume-ls -l help --description '.'
complete -c podman-volume-ls -l noheading --description '.'
complete -c podman-volume-ls -l quiet -s q --description '.'

