# podman-pod-kill
# Autogenerated from man page /usr/share/man/man1/podman-pod-kill.1.gz
complete -c podman-pod-kill -l all -s a --description '.'
complete -c podman-pod-kill -l latest -s l --description '.'
complete -c podman-pod-kill -l signal -s s --description '.'

