# podman-container-cleanup
# Autogenerated from man page /usr/share/man/man1/podman-container-cleanup.1.gz
complete -c podman-container-cleanup -l all -s a --description '.'
complete -c podman-container-cleanup -l exec --description '.'
complete -c podman-container-cleanup -l latest -s l --description '.'
complete -c podman-container-cleanup -l rm --description '.'
complete -c podman-container-cleanup -l rmi --description '.'

