# podman-system-df
# Autogenerated from man page /usr/share/man/man1/podman-system-df.1.gz
complete -c podman-system-df -l format --description '.'
complete -c podman-system-df -l verbose -s v --description '.'

