# podman-image-prune
# Autogenerated from man page /usr/share/man/man1/podman-image-prune.1.gz
complete -c podman-image-prune -l all -s a --description '.'
complete -c podman-image-prune -l filter --description '.'
complete -c podman-image-prune -l force -s f --description '.'
complete -c podman-image-prune -l help -s h --description '.'

