# podman-container-restore
# Autogenerated from man page /usr/share/man/man1/podman-container-restore.1.gz
complete -c podman-container-restore -l all -s a --description '.'
complete -c podman-container-restore -l keep -s k --description '.'
complete -c podman-container-restore -l latest -s l --description '.'
complete -c podman-container-restore -l ignore-rootfs --description '.'
complete -c podman-container-restore -l ignore-static-ip --description '.'
complete -c podman-container-restore -l ignore-static-mac --description '.'
complete -c podman-container-restore -l ignore-volumes --description '.'
complete -c podman-container-restore -l import -s i --description '.'
complete -c podman-container-restore -l import-previous --description '.'
complete -c podman-container-restore -l name -s n --description '.'
complete -c podman-container-restore -l pod --description '.'
complete -c podman-container-restore -l publish -s p --description '.'
complete -c podman-container-restore -l tcp-established --description '.'

