# podman-pod-inspect
# Autogenerated from man page /usr/share/man/man1/podman-pod-inspect.1.gz
complete -c podman-pod-inspect -l latest -s l --description '.'
complete -c podman-pod-inspect -l format -s f --description '.'

