# podman-exec
# Autogenerated from man page /usr/share/man/man1/podman-exec.1.gz
complete -c podman-exec -l detach -s d --description '.'
complete -c podman-exec -l detach-keys --description '.'
complete -c podman-exec -l env -s e --description '.'
complete -c podman-exec -l env-file --description '.'
complete -c podman-exec -l interactive -s i --description '.'
complete -c podman-exec -l latest -s l --description '.'
complete -c podman-exec -l preserve-fds --description '.'
complete -c podman-exec -l privileged --description '.'
complete -c podman-exec -l tty -s t --description '.'
complete -c podman-exec -l user -s u --description '.'
complete -c podman-exec -l workdir -s w --description '.'

