# podman-pod-ps
# Autogenerated from man page /usr/share/man/man1/podman-pod-ps.1.gz
complete -c podman-pod-ps -l ctr-names --description '.'
complete -c podman-pod-ps -l ctr-ids --description '.'
complete -c podman-pod-ps -l ctr-status --description '.'
complete -c podman-pod-ps -l latest -s l --description '.'
complete -c podman-pod-ps -l noheading --description '.'
complete -c podman-pod-ps -l no-trunc --description '.'
complete -c podman-pod-ps -l ns --description '.'
complete -c podman-pod-ps -l quiet -s q --description '.'
complete -c podman-pod-ps -l format --description '.'
complete -c podman-pod-ps -l sort --description '.'
complete -c podman-pod-ps -l filter -s f --description '.'
complete -c podman-pod-ps -l help -s h --description '.'

