# podman-volume-create
# Autogenerated from man page /usr/share/man/man1/podman-volume-create.1.gz
complete -c podman-volume-create -l driver --description '.'
complete -c podman-volume-create -l help --description '.'
complete -c podman-volume-create -l label -s l --description '.'
complete -c podman-volume-create -l opt -s o --description '.'

