# podman-version
# Autogenerated from man page /usr/share/man/man1/podman-version.1.gz
complete -c podman-version -l help -s h --description '.'
complete -c podman-version -l format -s f --description '.'

