# podman-image-tree
# Autogenerated from man page /usr/share/man/man1/podman-image-tree.1.gz
complete -c podman-image-tree -l help -s h --description '.'
complete -c podman-image-tree -l whatrequires --description '.'

