# podman-pod-unpause
# Autogenerated from man page /usr/share/man/man1/podman-pod-unpause.1.gz
complete -c podman-pod-unpause -l all -s a --description '.'
complete -c podman-pod-unpause -l latest -s l --description '.'

