# podman-wait
# Autogenerated from man page /usr/share/man/man1/podman-wait.1.gz
complete -c podman-wait -l condition --description '.'
complete -c podman-wait -l help -s h --description '.'
complete -c podman-wait -l interval -s i --description '.'
complete -c podman-wait -l latest -s l --description '.'

