# podman-login
# Autogenerated from man page /usr/share/man/man1/podman-login.1.gz
complete -c podman-login -l authfile --description '.'
complete -c podman-login -l cert-dir --description '.'
complete -c podman-login -l get-login --description '.'
complete -c podman-login -l help -s h --description '.'
complete -c podman-login -l password -s p --description '.'
complete -c podman-login -l password-stdin --description '.'
complete -c podman-login -l tls-verify --description '.'
complete -c podman-login -l username -s u --description '.'
complete -c podman-login -l verbose -s v --description '.'

