# podman-logs
# Autogenerated from man page /usr/share/man/man1/podman-logs.1.gz
complete -c podman-logs -l follow -s f --description '.'
complete -c podman-logs -l latest -s l --description '.'
complete -c podman-logs -l names -s n --description '.'
complete -c podman-logs -l since --description '.'
complete -c podman-logs -l until --description '.'
complete -c podman-logs -l tail --description '.'
complete -c podman-logs -l timestamps -s t --description '.'

