# podman-container-checkpoint
# Autogenerated from man page /usr/share/man/man1/podman-container-checkpoint.1.gz
complete -c podman-container-checkpoint -l all -s a --description '.'
complete -c podman-container-checkpoint -l compress -s c --description '.'
complete -c podman-container-checkpoint -l export -s e --description '.'
complete -c podman-container-checkpoint -l ignore-rootfs --description '.'
complete -c podman-container-checkpoint -l ignore-volumes --description '.'
complete -c podman-container-checkpoint -l keep -s k --description '.'
complete -c podman-container-checkpoint -l latest -s l --description '.'
complete -c podman-container-checkpoint -l leave-running -s R --description '.'
complete -c podman-container-checkpoint -l pre-checkpoint -s P --description '.'
complete -c podman-container-checkpoint -l tcp-established --description '.'
complete -c podman-container-checkpoint -l with-previous --description '.'

