# podman-attach
# Autogenerated from man page /usr/share/man/man1/podman-attach.1.gz
complete -c podman-attach -l detach-keys --description '.'
complete -c podman-attach -l latest -s l --description '.'
complete -c podman-attach -l no-stdin --description '.'
complete -c podman-attach -l sig-proxy --description '.'

