# podman-pull
# Autogenerated from man page /usr/share/man/man1/podman-pull.1.gz
complete -c podman-pull -l all-tags --description '.'
complete -c podman-pull -l arch --description '.'
complete -c podman-pull -l authfile --description '.'
complete -c podman-pull -l cert-dir --description '.'
complete -c podman-pull -l creds --description '.'
complete -c podman-pull -l disable-content-trust --description '.'
complete -c podman-pull -l help -s h --description '.'
complete -c podman-pull -l os --description '.'
complete -c podman-pull -l platform --description '.'
complete -c podman-pull -l quiet -s q --description '.'
complete -c podman-pull -l tls-verify --description '.'
complete -c podman-pull -l variant --description '.'

