# podman-image-trust
# Autogenerated from man page /usr/share/man/man1/podman-image-trust.1.gz
complete -c podman-image-trust -l help -s h --description '.'
complete -c podman-image-trust -l pubkeysfile -s f --description '.'
complete -c podman-image-trust -l type -s t --description '.'
complete -c podman-image-trust -l raw --description '.'
complete -c podman-image-trust -l json -s j --description '.'

