# podman-pod-stats
# Autogenerated from man page /usr/share/man/man1/podman-pod-stats.1.gz
complete -c podman-pod-stats -l all -s a --description '.'
complete -c podman-pod-stats -l latest -s l --description '.'
complete -c podman-pod-stats -l no-reset --description '.'
complete -c podman-pod-stats -l no-stream --description '.'
complete -c podman-pod-stats -l format --description '.'

