# podman-stats
# Autogenerated from man page /usr/share/man/man1/podman-stats.1.gz
complete -c podman-stats -l all -s a --description '.'
complete -c podman-stats -l latest -s l --description '.'
complete -c podman-stats -l no-reset --description '.'
complete -c podman-stats -l no-stream --description '.'
complete -c podman-stats -l format --description '.'

