# podman-images
# Autogenerated from man page /usr/share/man/man1/podman-images.1.gz
complete -c podman-images -l all -s a --description '.'
complete -c podman-images -l digests --description '.'
complete -c podman-images -l filter -s f --description '.'
complete -c podman-images -l format --description '.'
complete -c podman-images -l history --description '.'
complete -c podman-images -l noheading -s n --description '.'
complete -c podman-images -l no-trunc --description '.'
complete -c podman-images -l quiet -s q --description '.'
complete -c podman-images -l sort --description '.'

