# podman-pod-restart
# Autogenerated from man page /usr/share/man/man1/podman-pod-restart.1.gz
complete -c podman-pod-restart -l all -s a --description '.'
complete -c podman-pod-restart -l latest -s l --description '.'

