# podman-events
# Autogenerated from man page /usr/share/man/man1/podman-events.1.gz
complete -c podman-events -l help --description '.'
complete -c podman-events -l format --description '.'
complete -c podman-events -l filter --description '.'
complete -c podman-events -l since --description '.'
complete -c podman-events -l until --description '.'

