# podman-volume-prune
# Autogenerated from man page /usr/share/man/man1/podman-volume-prune.1.gz
complete -c podman-volume-prune -l force -s f --description '.'
complete -c podman-volume-prune -l filter --description '.'
complete -c podman-volume-prune -l help --description '.'

