# podman-rm
# Autogenerated from man page /usr/share/man/man1/podman-rm.1.gz
complete -c podman-rm -l all -s a --description '.'
complete -c podman-rm -l cidfile --description '.'
complete -c podman-rm -l force -s f --description '.'
complete -c podman-rm -l ignore -s i --description '.'
complete -c podman-rm -l latest -s l --description '.'
complete -c podman-rm -l volumes -s v --description '.'

