# podman-pod-pause
# Autogenerated from man page /usr/share/man/man1/podman-pod-pause.1.gz
complete -c podman-pod-pause -l all -s a --description '.'
complete -c podman-pod-pause -l latest -s l --description '.'

