# podman-system-reset
# Autogenerated from man page /usr/share/man/man1/podman-system-reset.1.gz
complete -c podman-system-reset -l force -s f --description '.'
complete -c podman-system-reset -l help -s h --description '.'

