# podman-image-sign
# Autogenerated from man page /usr/share/man/man1/podman-image-sign.1.gz
complete -c podman-image-sign -l help -s h --description '.'
complete -c podman-image-sign -l all -s a --description '.'
complete -c podman-image-sign -l cert-dir --description '.'
complete -c podman-image-sign -l directory -s d --description '.'
complete -c podman-image-sign -l sign-by --description '.'

