# podman-ps
# Autogenerated from man page /usr/share/man/man1/podman-ps.1.gz
complete -c podman-ps -l all -s a --description '.'
complete -c podman-ps -l external --description '.'
complete -c podman-ps -l filter -s f --description '.'
complete -c podman-ps -l format --description '.'
complete -c podman-ps -l help -s h --description '.'
complete -c podman-ps -l last -s n --description '.'
complete -c podman-ps -l latest -s l --description '.'
complete -c podman-ps -l namespace -l ns --description '.'
complete -c podman-ps -l noheading --description '.'
complete -c podman-ps -l no-trunc --description '.'
complete -c podman-ps -l pod -s p --description '.'
complete -c podman-ps -l quiet -s q --description '.'
complete -c podman-ps -l sort --description '.'
complete -c podman-ps -l size -s s --description '.'
complete -c podman-ps -l sync --description '.'
complete -c podman-ps -l watch -s w --description '.'

