# podman-container-exists
# Autogenerated from man page /usr/share/man/man1/podman-container-exists.1.gz
complete -c podman-container-exists -l external --description '.'
complete -c podman-container-exists -s h -l help --description 'Prints usage statement.'

