# podman-system-prune
# Autogenerated from man page /usr/share/man/man1/podman-system-prune.1.gz
complete -c podman-system-prune -l all -s a --description '.'
complete -c podman-system-prune -l filter --description '.'
complete -c podman-system-prune -l force -s f --description '.'
complete -c podman-system-prune -l help -s h --description '.'
complete -c podman-system-prune -l volumes --description '.'

