# podman-commit
# Autogenerated from man page /usr/share/man/man1/podman-commit.1.gz
complete -c podman-commit -l author -s a --description '.'
complete -c podman-commit -l change -s c --description '.'
complete -c podman-commit -l format -s f --description '.'
complete -c podman-commit -l iidfile --description '.'
complete -c podman-commit -l include-volumes --description '.'
complete -c podman-commit -l message -s m --description '.'
complete -c podman-commit -l pause -s p --description '.'
complete -c podman-commit -l quiet -s q --description '.'

