# podman-container-runlabel
# Autogenerated from man page /usr/share/man/man1/podman-container-runlabel.1.gz
complete -c podman-container-runlabel -l authfile --description '.'
complete -c podman-container-runlabel -l display --description '.'
complete -c podman-container-runlabel -l cert-dir --description '.'
complete -c podman-container-runlabel -l creds --description '.'
complete -c podman-container-runlabel -l help -s h --description '.'
complete -c podman-container-runlabel -l name -s n --description '.'
complete -c podman-container-runlabel -l quiet -s q --description '.'
complete -c podman-container-runlabel -l replace --description '.'
complete -c podman-container-runlabel -l tls-verify --description '.'

