# podman-pod-start
# Autogenerated from man page /usr/share/man/man1/podman-pod-start.1.gz
complete -c podman-pod-start -l all -s a --description '.'
complete -c podman-pod-start -l latest -s l --description '.'
complete -c podman-pod-start -l pod-id-file --description '.'

