# podman-push
# Autogenerated from man page /usr/share/man/man1/podman-push.1.gz
complete -c podman-push -l authfile --description '.'
complete -c podman-push -l creds --description '.'
complete -c podman-push -l cert-dir --description '.'
complete -c podman-push -l compress --description '.'
complete -c podman-push -l digestfile --description '.'
complete -c podman-push -l disable-content-trust --description '.'
complete -c podman-push -l format -s f --description '.'
complete -c podman-push -l quiet -s q --description '.'
complete -c podman-push -l remove-signatures --description '.'
complete -c podman-push -l sign-by --description '.'
complete -c podman-push -l tls-verify --description '.'

