# podman-restart
# Autogenerated from man page /usr/share/man/man1/podman-restart.1.gz
complete -c podman-restart -l all -s a --description '.'
complete -c podman-restart -l latest -s l --description '.'
complete -c podman-restart -l running --description '.'
complete -c podman-restart -l time -s t --description '.'

