# podman-volume-inspect
# Autogenerated from man page /usr/share/man/man1/podman-volume-inspect.1.gz
complete -c podman-volume-inspect -l all -s a --description '.'
complete -c podman-volume-inspect -l format -s f --description '.'
complete -c podman-volume-inspect -l help --description '.'

