# podman-stop
# Autogenerated from man page /usr/share/man/man1/podman-stop.1.gz
complete -c podman-stop -l all -s a --description '.'
complete -c podman-stop -l cidfile --description '.'
complete -c podman-stop -l ignore -s i --description '.'
complete -c podman-stop -l latest -s l --description '.'
complete -c podman-stop -l time -s t --description '.'

