# podman-export
# Autogenerated from man page /usr/share/man/man1/podman-export.1.gz
complete -c podman-export -l output -s o --description '.'
complete -c podman-export -l help -s h --description '.'

