# podman-start
# Autogenerated from man page /usr/share/man/man1/podman-start.1.gz
complete -c podman-start -l attach -s a --description '.'
complete -c podman-start -l detach-keys --description '.'
complete -c podman-start -l interactive -s i --description '.'
complete -c podman-start -l latest -s l --description '.'
complete -c podman-start -l sig-proxy --description '.'
complete -c podman-start -l all --description '.'
complete -c podman-start -l filter -s f --description '.'

