# pyreverse
# Autogenerated from man page /usr/share/man/man1/pyreverse.1.gz
complete -c pyreverse -s h -l help --description 'show help message and exit.'
complete -c pyreverse -o 'p<name>' -l project --description 'set project name to <name> if not using -c option.  (default:\'No Name\').'
complete -c pyreverse -l ignore --description 'add files or directories to the blacklist.'
complete -c pyreverse -o 'f<mode>' -l filter-mode --description 'filter attributes and functions according to <mode>.'
complete -c pyreverse -o 'd<file>' -l diadefs --description 'create diagram according to the diagram definitions in <file>.'
complete -c pyreverse -s c -l class --description 'create a class diagram with all classes related to <class>  [current: none] t…'
complete -c pyreverse -s a -l show-ancestors --description 'show <ancestor> generations of ancestor classes not in <projects>.'
complete -c pyreverse -s A -l all-ancestors --description 'show all ancestors off all classes in <projects> [current: none].'
complete -c pyreverse -s s -l show-associated --description 'show <ass_level> associated classes.'
complete -c pyreverse -s S -l all-associated --description 'show recursively all associated off all associated classes [current: none].'
complete -c pyreverse -s b -l builtin --description 'include builtin objects in representation of classes [current: False].'
complete -c pyreverse -s m -l module-names --description 'include module name in representation of classes.'
complete -c pyreverse -s k -l only-classnames --description 'don\'t show attributes and methods in the class boxes;   this disables -f valu…'
complete -c pyreverse -s o -l output --description 'create a *. <format> output file if format available.'
complete -c pyreverse -o a1 -o s1 --description 'diagram  of the <project> modules, while -m will show the full module  path o…'

