# qtool
# Autogenerated from man page /usr/share/man/man8/qtool.8.gz
complete -c qtool -s b --description 'Bounce all of the messages specified by source.'
complete -c qtool -s C --description 'Specify the sendmail config file.  Defaults to /etc/mail/sendmail. cf.'
complete -c qtool -s d --description 'Delete all of the messages specified by source.'
complete -c qtool -s e --description 'Evaluate perl_expression for each queue file as specified by source.'
complete -c qtool -s Q --description 'Operate on quarantined items (queue control file begins with hf instead of qf…'
complete -c qtool -s s --description 'Move only the queue files specified by source that have a modification time o…'

