# quickbook
# Autogenerated from man page /usr/share/man/man1/quickbook.1.gz
complete -c quickbook -l help --description 'produce help message.'
complete -c quickbook -l version --description 'print version string.'
complete -c quickbook -l no-pretty-print --description 'disable XML pretty printing.'
complete -c quickbook -l indent --description 'indent spaces.'
complete -c quickbook -l linewidth --description 'line width.'
complete -c quickbook -l input-file --description 'input file.'
complete -c quickbook -l output-file --description 'output file.'
complete -c quickbook -l debug --description 'debug mode (for developers).'
complete -c quickbook -l ms-errors --description 'use Microsoft Visual Studio style error & warn message format.'
complete -c quickbook -s I -l include-path --description 'SEE ALSO The full documentation for Quickbook is maintained in HTML; see /usr…'

