# runq
# Autogenerated from man page /usr/share/man/man8/runq.sendmail.8.gz
complete -c runq -l help --description 'Print a usage message on standard output and exit successfully.'
complete -c runq -l version --description 'Print version information on standard output then exit successfully.'

