# sfconv
# Autogenerated from man page /usr/share/man/man1/sfconv.1.gz
complete -c sfconv -o 8u -o u8 --description 'conversion direction: 8-bit to Unicode or vice versa.'
complete -c sfconv -s c --description 'specifies XML control file.'
complete -c sfconv -s i --description 'specifies filename of input SF file.'
complete -c sfconv -s o --description 'specifies filename for converted output  In addition, the following optional …'
complete -c sfconv -s d --description 'directory where mapping files ( . tec files) are to be found.'
complete -c sfconv -o utf8 -o be -o le --description 'Unicode encoding form: UTF-8, UTF-16BE, or UTF16-LE (default is UTF8 for outp…'
complete -c sfconv -o bom --description '(only when mapping to Unicode) write initial BOM to the output file.'

