# sg_dd
# Autogenerated from man page /usr/share/man/man8/sg_dd.8.gz
complete -c sg_dd -s d -l dry-run --description 'does all the command line parsing and preparation but bypasses the actual cop…'
complete -c sg_dd -s h -l help --description 'outputs usage message and exits.'
complete -c sg_dd -s v -l verbose --description 'when used once, this is equivalent to verbose=1.  When used twice (e. g.'
complete -c sg_dd -s V -l version --description 'outputs version number information and exits.'

