# slurmd
# Autogenerated from man page /usr/share/man/man8/slurmd.8.gz
complete -c slurmd -s b --description 'Report node rebooted when daemon restarted.  Used for testing purposes.'
complete -c slurmd -s c --description 'Clear system locks as needed.'
complete -c slurmd -s C --description 'Print actual hardware configuration and exit.'
complete -c slurmd -s d --description 'Specify the fully qualified pathname to the slurmstepd program to be used for…'
complete -c slurmd -s D --description 'Run slurmd in the foreground.'
complete -c slurmd -s f --description 'Read configuration from the specified file.  See NOTES below.'
complete -c slurmd -s G --description 'Print Generic RESource (GRES) configuration (based upon slurm.'
complete -c slurmd -s h --description 'Help; print a brief summary of command options.'
complete -c slurmd -s L --description 'Write log messages to the specified file.'
complete -c slurmd -s M --description 'Lock slurmd pages into system memory using mlockall (2) to disable paging of …'
complete -c slurmd -s n --description 'Set the daemon\'s nice value to the specified value, typically a negative numb…'
complete -c slurmd -s N --description 'Run the daemon with the given nodename.'
complete -c slurmd -s v --description 'Verbose operation.  Multiple -v\'s increase verbosity.'
complete -c slurmd -s V -l version --description 'Print version information and exit.'

