# sos-mask
# Autogenerated from man page /usr/share/man/man1/sos-mask.1.gz
complete -c sos-mask -l domains --description 'Provide a comma-delimited list of domain names to obfuscate, in addition to t…'
complete -c sos-mask -l keywords --description 'Provide a comma-delimited list of keywords to scrub in addition to the defaul…'
complete -c sos-mask -l keyword-file --description 'Provide a file that contains a list of keywords that should be obfuscated.'
complete -c sos-mask -l map-file --description 'Provide a location to a valid mapping file to use as a reference for existing…'
complete -c sos-mask -l jobs --description 'The number of concurrent archives to process, if more than one.'
complete -c sos-mask -l clean -l mask --description '.'
complete -c sos-mask -l no-update --description 'Do not write the mapping file contents to /etc/sos/cleaner/default_mapping MA…'

