# symilar
# Autogenerated from man page /usr/share/man/man1/symilar.1.gz
complete -c symilar -s h -l help --description 'show help message and exit.'
complete -c symilar -s d -l duplicates --description 'minimum number of identical lines that should trigger a similarity message.'
complete -c symilar -s i -l ignore-comments --description 'ignore differences concerning only stuff behind a \'#\' (Python comments).'

