# teckit_compile
# Autogenerated from man page /usr/share/man/man1/teckit_compile.1.gz
complete -c teckit_compile -s o --description 'output compiled table (. tec) file ("-" for stdout).'
complete -c teckit_compile -s u --description 'read source text as UTF8 even if no BOM found.'
complete -c teckit_compile -s x --description 'generate XML representation rather than compiled table.'
complete -c teckit_compile -s z --description 'generate uncompressed table format Further Information For further informatio…'

