# texdoc
# Autogenerated from man page /usr/share/man/man1/texdoc.1.gz
complete -c texdoc -s w -l view --description 'Use view mode: start a viewer.  (default) .'
complete -c texdoc -s m -l mixed --description 'Use mixed mode (view or list).'
complete -c texdoc -s l -l list --description 'Use list mode: show a list of results.'
complete -c texdoc -s s -l showall --description 'Use showall mode: show also "bad" results.'
complete -c texdoc -s i -l interact --description 'Use interactive menus.  (default) .'
complete -c texdoc -s I -l nointeract --description 'Use plain lists, no interaction required.'
complete -c texdoc -s M -l machine --description 'Machine-readable output for lists (implies -I).'
complete -c texdoc -s q -l quiet --description 'Suppress warnings and most error messages.'
complete -c texdoc -s v -l verbose --description 'Print additional information (e. g. , viewer command).'
complete -c texdoc -s D -l debug --description 'Activate all debug output (equal to "--debug=all").'
complete -c texdoc -s d --description 'Activate debug output restricted to the categories specified in LIST.'

