# txtconv
# Autogenerated from man page /usr/share/man/man1/txtconv.1.gz
complete -c txtconv -s i --description 'input file.'
complete -c txtconv -s o --description 'output file . PP Optional arguments:.'
complete -c txtconv -s t --description 'compiled TECkit mapping (. tec) file.'
complete -c txtconv -s r --description 'reverse (RHS->LHS, or Unicode->Byte) mapping.'
complete -c txtconv -o if --description 'input encoding form.'
complete -c txtconv -o of --description 'output encoding form.'
complete -c txtconv -o nobom --description 'don\'t write a BOM to Unicode output.'
complete -c txtconv -o nf --description 'apply NFC or NFD normalization to Unicode output.'

