# unmunge
# Autogenerated from man page /usr/share/man/man1/unmunge.1.gz
complete -c unmunge -s h -l help --description 'Display a summary of the command-line options.'
complete -c unmunge -s L -l license --description 'Display license information.'
complete -c unmunge -s V -l version --description 'Display version information.'
complete -c unmunge -s i -l input --description 'Input the credential from the specified file.'
complete -c unmunge -s n -l no-output --description 'Discard all output.'
complete -c unmunge -s m -l metadata --description 'Output metadata to the specified file.'
complete -c unmunge -s o -l output --description 'Output the payload to the specified file.'
complete -c unmunge -s k -l keys --description 'Specify a subset of metadata keys to output.'
complete -c unmunge -s K -l list-keys --description 'Display a list of metadata keys.'
complete -c unmunge -s S -l socket --description 'Specify the local domain socket for connecting with munged.'

