# updatedb
# Autogenerated from man page /usr/share/man/man1/updatedb.1.gz
complete -c updatedb -l findoptions -o 'option2...\'' --description 'Global options to pass on to find.'
complete -c updatedb -l localpaths --description 'Non-network directories to put in the database.  Default is /.'
complete -c updatedb -l netpaths --description 'Network (NFS, AFS, RFS, etc. ) directories to put in the database.'
complete -c updatedb -l prunepaths --description 'Directories to not put in the database, which would otherwise be.'
complete -c updatedb -l prunefs --description 'File systems to not put in the database, which would otherwise be.'
complete -c updatedb -l output --description 'The database file to build.  Default is system-dependent.'
complete -c updatedb -l localuser --description 'The user to search non-network directories as, using su(1).'
complete -c updatedb -l netuser --description 'The user to search network directories as, using su(1).  Default is daemon.'
complete -c updatedb -l dbformat --description 'Create the database in format F.   The default format is called LOCATE02.'
complete -c updatedb -l version --description 'Print the version number of  updatedb and exit.'
complete -c updatedb -l help --description 'Print a summary of the options to updatedb and exit.'

