# uptex
# Autogenerated from man page /usr/share/man/man1/uptex.1.gz
complete -c uptex -o kanji --description 'Sets the input Japanese Kanji code.'
complete -c uptex -o kanji-internal --description 'Sets the internal Kanji code.   The string can be either R euc , and R sjis .'
complete -c uptex -o enc --description 'In this version of (e-)(u)p, enc extensions are not available.'

