# xetex
# Autogenerated from man page /usr/share/man/man1/xetex.1.gz
complete -c xetex -o no-pdf --description 'Generate Xe\\*(TX\'s extended DVI (. xdv) output instead of pdf.'
complete -c xetex -o output-driver --description 'Run  cmd instead of xdvipdfmx to translate xdv to pdf.'
complete -c xetex -o papersize --description 'Set pdf media size to string .'
complete -c xetex -o draftmode --description '.'
complete -c xetex -o enc --description '.'
complete -c xetex -o ipc --description '.'
complete -c xetex -o ipc-start --description '.'
complete -c xetex -o translate-file --description '.'

