# xine-list-1
# Autogenerated from man page /usr/share/man/man1/xine-list-1.2.1.gz
complete -c xine-list-1 -s m --description '--mime-types List the MIME types known to xine-lib.'
complete -c xine-list-1 -s e --description '--extensions List the file types (filename extensions) known to xine-lib.'
complete -c xine-list-1 -s a --description '--all List the MIME types known to xine-lib, along with their filename extens…'
complete -c xine-list-1 -l mime-types --description 'List the MIME types known to xine-lib.  (This is the default action. ).'
complete -c xine-list-1 -l extensions --description 'List the file types (filename extensions) known to xine-lib.'
complete -c xine-list-1 -l all --description 'List the MIME types known to xine-lib, along with their filename extensions a…'
complete -c xine-list-1 -s p --description '.'
complete -c xine-list-1 -l pretty-print --description 'Add line feeds; print each item on a line of its own.'

