# xine-config
# Autogenerated from man page /usr/share/man/man1/xine-config.1.gz
complete -c xine-config -l version --description '--modversion .'
complete -c xine-config -l libs --description 'TQ 8   --cflags . TQ 8   --objcflags Passed on unmodified.'
complete -c xine-config -l bindir --description 'TQ 8   --plugindir . TQ 8   --datadir . TQ 8   --scriptdir .'
complete -c xine-config -l prefix --description '--define-variable=prefix=PREFIX .'
complete -c xine-config -l modversion --description '.'
complete -c xine-config -l cflags --description '.'
complete -c xine-config -l objcflags --description 'Passed on unmodified.'
complete -c xine-config -l plugindir --description '.'
complete -c xine-config -l datadir --description '.'
complete -c xine-config -l scriptdir --description '.'
complete -c xine-config -l localedir --description '.'
complete -c xine-config -l variable --description '.'
complete -c xine-config -l define-variable --description '.'
complete -c xine-config -l exec-prefix --description '.'

