# xmlsec1-config
# Autogenerated from man page /usr/share/man/man1/xmlsec1-config.1.gz
complete -c xmlsec1-config -l cflags --description 'print pre-processor and compiler flags.'
complete -c xmlsec1-config -l libs --description 'print library linking information.'
complete -c xmlsec1-config -l prefix --description 'print the default XMLSEC prefix folder.'
complete -c xmlsec1-config -l exec-prefix --description 'print the default XMLSEC executable prefix folder.'
complete -c xmlsec1-config -l libdir --description 'print the default XMLSEC libraries folder.'
complete -c xmlsec1-config -l crypto --description 'print the default crypto library name.'
complete -c xmlsec1-config -l help --description 'display this help and exit.'
complete -c xmlsec1-config -l version --description 'output version information.'

